version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "micrometer"
    open-pull-requests-limit: 10
    # Avoid any Dependabot branch name collisions
    pull-request-branch-name:
      separator: "-"
    labels: 
      - "micrometer"
      - "dependencies"
