# partial playbook just for this project to be able to compile documentation without pushing it to GitHub
# usage: antora generate antora-playbook.yml
site:
  title: SmallRye Metrics only documentation
  start_page: smallrye-metrics::index.adoc
content:
  sources:
  - url: ..
    start_path: doc
    branches: HEAD
ui:
  bundle:
    url: https://github.com/smallrye/smallrye-antora-ui/blob/master/build/ui-bundle.zip?raw=true
    snapshot: true
